name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install NPM
        run: npm i -g npm@8 --registry=https://registry.npmjs.org
      
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run
        run: npx ts-node index.ts
        
  deploy-development:
    needs: [build]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Run
        run: echo Deploying to Development

  deploy-staging:
    needs: [build]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Run
        run: echo Deploying to Staging

  deploy-production:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run
        run: echo Deploying to Production
